dist: bionic

language: ruby

rvm: 2.7.0

install:
  - sudo apt update && sudo apt install mediainfo
  - gem install bundler
  - bundle install
  - mkdir -p /tmp/video/TV

script:
  - bundle exec rake
  - cp .videolib.yml ~/
  - ./videolib.rb
