version: 2.1

jobs:
  build:
    docker:
      # Keep in sync with .ruby-version
      - image: cimg/ruby:4.0.7
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install -y mediainfo
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Set up test directory
          command: mkdir -p /tmp/video/TV
      - run:
          name: Run rake tests
          command: bundle exec rake
      - run:
          name: Set up videolib config
          command: cp videolib.yml ~/.videolib.yml
      - run:
          name: Run the script
          command: ./videolib.rb
